<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SubClient;

class SubClientSeeder extends Seeder
{

    public function run(): void
    {
        $data = [

            [
                'id' => 1,
                'client_id' => 1,
                'name' => 'CPP - CEMENTOS PACASMAYO - PIURA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'client_id' => 1,
                'name' => 'CPL - CEMENTOS PACASMAYO - LA LIBERTAD',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'client_id' => 16,
                'name' => 'CEP-CLEAN ENERGY DEL PERU',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'client_id' => 14,
                'name' => 'PMK - PROCESO MUCHIK',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'client_id' => 12,
                'name' => 'PAG-PLASTICOS AGRICOLAS Y GEOMEMBRANAS',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'client_id' => 11,
                'name' => 'GRL-GOBIERNO REGIONAL LAMBAYEQUE',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'client_id' => 8,
                'name' => 'CMM-MISKI MAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'client_id' => 7,
                'name' => 'CARTAVIO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'client_id' => 4,
                'name' => 'AO - AGROLMOS',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'client_id' => 3,
                'name' => 'ASJ-AGROINDUSTRIAS SAN JACINTO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'client_id' => 5,
                'name' => 'ANDALUCITA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'client_id' => 6,
                'name' => 'CG - CASA GRANDE',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'client_id' => 20,
                'name' => 'ASL-AGROINDUSTRIAL LAREDO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'client_id' => 2,
                'name' => 'AA - AGROAURORA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'client_id' => 9,
                'name' => 'DSM',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 16,
                'client_id' => 10,
                'name' => 'GAT',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'client_id' => 17,
                'name' => 'HAY-PESQUERA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'client_id' => 13,
                'name' => 'DNP-DINO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'client_id' => 19,
                'name' => 'CORPORACION PLASTIC GL S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'client_id' => 18,
                'name' => 'ECOSAC AGRICOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'client_id' => 15,
                'name' => 'IPR-INVERSIONES PRISCO S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'client_id' => 21,
                'name' => 'TRU-TRUPAL S.A',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'client_id' => 22,
                'name' => 'ER-EL ROCIO S.A',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'client_id' => 23,
                'name' => 'AR - SOCIEDAD AGRICOLA RAPEL SAC',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'client_id' => 24,
                'name' => 'PPP - PLANTA DE POSTES PIURA S.R.L',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'client_id' => 25,
                'name' => 'CONGRESO DE LA REPUBLICA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'client_id' => 26,
                'name' => 'CAA- CORPORACION ACEROS AREQUIPA S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'client_id' => 27,
                'name' => 'MAL-MONTERREY AZUCARERA LOJANA C.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'client_id' => 28,
                'name' => 'CAYNARACHI S.A',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'client_id' => 29,
                'name' => 'CSJ - CONSORCIO CARSOL - JRM S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'client_id' => 30,
                'name' => 'ADC-AGRICOLA DEL CHIRA S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 32,
                'client_id' => 31,
                'name' => 'PDP-PETROLEOS DEL PERU PETROPERU SA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'client_id' => 33,
                'name' => 'UNA- UNNA ENERGIA S.A',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'client_id' => 34,
                'name' => 'UNE -UNIV.NAC.DE EDUC. ENRIQUE GUZMAN Y VALLE',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'client_id' => 35,
                'name' => 'OCS - OCEANO SEAFOOD S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'client_id' => 36,
                'name' => 'MIC - MILICIC PERU S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'client_id' => 37,
                'name' => 'CHR - CHINA RAILWAY N° 10 ENGINEERING GROUP CO., LTD SUCURSAL DEL PERU',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'client_id' => 38,
                'name' => 'YOF-YOFC PERU S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'client_id' => 39,
                'name' => 'SHE-SUNSHINE EXPORT S.A.C',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'client_id' => 40,
                'name' => 'PAL - PESQUERA ALTAIR S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'client_id' => 40,
                'name' => 'PAL-PESQUERA ALTAIR S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'client_id' => 41,
                'name' => 'UNP - UNIVERSIDAD NACIONAL DE PIURA ',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'client_id' => 43,
                'name' => 'LDN-LADRINORTE S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'client_id' => 44,
                'name' => 'HJH - HOSPITAL JOSE HERNÁN SOTO CADENILLAS',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'client_id' => 45,
                'name' => 'VTP - VITAPRO S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'client_id' => 46,
                'name' => 'AGC - AGROFUTURA COMPANY S.A.C. ',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'client_id' => 47,
                'name' => 'IMT- INGEMMET',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 49,
                'client_id' => 48,
                'name' => 'DNP - DANPER AGRICOLA OLMOS S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'client_id' => 49,
                'name' => 'CPR',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'client_id' => 50,
                'name' => 'AVO-AVOAMERICA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'client_id' => 51,
                'name' => 'GAL',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'client_id' => 52,
                'name' => 'APC - AVOCADO PACKING COMPANY',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'client_id' => 53,
                'name' => 'MPW - MANPOWER PROFESSIONAL SERVICES S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'client_id' => 54,
                'name' => 'DPT - DANPER TRUJILLO S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'client_id' => 55,
                'name' => 'JPS',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'client_id' => 56,
                'name' => 'SPS -  SUPERMERCADOS PERUANOS S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'client_id' => 57,
                'name' => 'CONSORCIO PIURA - CSP',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'client_id' => 58,
                'name' => 'PAITA INGREDIENTS S.A.C. - PIS',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'client_id' => 59,
                'name' => 'TRANSPORTES Y SERVICIOS GENERALES LARA EIRL - TSG',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'client_id' => 60,
                'name' => 'EPS-ENTIDAD PRESTADORA DE SERVICIOS DE SANEAMIENTO GRAU',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'client_id' => 61,
                'name' => 'SFP-SUPERFOODS PERU S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 63,
                'client_id' => 62,
                'name' => 'ALS - ALMACENES SUDAMERICANOS S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 64,
                'client_id' => 63,
                'name' => 'VC - V&C S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
                'id' => 65,
                'client_id' => 64,
                'name' => 'CEYESA S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 66,
                'client_id' => 65,
                'name' => 'GDP - GASES DEL PACÍFICO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 67,
                'client_id' => 66,
                'name' => 'MTA - CONSORCIO MONTE AZUL S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 68,
                'client_id' => 67,
                'name' => 'MBM - MINERA BOROO MISQUICHILCA S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 69,
                'client_id' => 68,
                'name' => 'IMC - INMOBILIARIA LAS CUMBRES S.A.C',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 70,
                'client_id' => 69,
                'name' => 'ILC - INVERSIONES LA CRUZ S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 71,
                'client_id' => 70,
                'name' => 'MVS - MV SERVICIOS S.R.L.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 72,
                'client_id' => 71,
                'name' => 'KCP - KAESER COMPRESORES DE PERU S.R.L.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 74,
                'client_id' => 72,
                'name' => 'FMG-FAMEGSA E.I.R.L.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 75,
                'client_id' => 73,
                'name' => 'SBT - SMART BUSINESS TEC S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 76,
                'client_id' => 74,
                'name' => 'GCI - GLOBAL CITRUS INTERNATIONAL SOCIEDAD ANONIMA CERRADA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 77,
                'client_id' => 75,
                'name' => 'SGG - SERVICIOS GENERALES GADENN E.I.R.L.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 78,
                'client_id' => 76,
                'name' => 'FHT - F & H TRANSPORTES Y SERVICIOS SAC',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 79,
                'client_id' => 77,
                'name' => 'SEN - SENATI',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 80,
                'client_id' => 60,
                'name' => 'EPS - ENTIDAD PRESTADORA DE SERVICIOS DE SANEAMIENTO GRAU',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 81,
                'client_id' => 78,
                'name' => 'MRS - MARINASOL S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 82,
                'client_id' => 79,
                'name' => 'CPS - CITRICOS PERUANOS S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 84,
                'client_id' => 80,
                'name' => 'AI - AGROMAR INDUSTRIAL S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 85,
                'client_id' => 81,
                'name' => 'PUF-PUFFER PERU S.R.L',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 86,
                'client_id' => 82,
                'name' => 'NFM-NATIONAL FACILITIES MANAGEMENT S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 87,
                'client_id' => 83,
                'name' => 'LM - LARCO MAR S.A',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 88,
                'client_id' => 84,
                'name' => 'TAV-TECNICA AVICOLA S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 89,
                'client_id' => 85,
                'name' => 'PDM-PROVEEDORA DE PRODUCTOS MARINOS',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 90,
                'client_id' => 86,
                'name' => 'PSF-PERUVIAN SEA FOOD S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 91,
                'client_id' => 87,
                'name' => 'PPS-PRECISION PERU S.A. ',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 92,
                'client_id' => 88,
                'name' => 'EMC-EMBOTELLADORA CARAL S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 93,
                'client_id' => 89,
                'name' => 'MSX - MINERA SHOUXIN PERU S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 94,
                'client_id' => 90,
                'name' => 'IT -INDUSTRIAS DEL TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 95,
                'client_id' => 91,
                'name' => 'OA - OLEAGINOSAS AMAZONICAS S.A',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 96,
                'client_id' => 92,
                'name' => 'RFH- REFRIGERADOS FISHOLG & HIJOS ',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 97,
                'client_id' => 93,
                'name' => 'PAC-PRODUCTORA ANDINA DE CONGELADOS S.R.L.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 98,
                'client_id' => 95,
                'name' => 'EAP-EMPRESA AGROINDUSTRIAL POMALCA ',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 99,
                'client_id' => 96,
                'name' => 'LIF-LADRILLOS INKA FORTE S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 100,
                'client_id' => 96,
                'name' => 'LF-LADRILLOS FORTES S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 101,
                'client_id' => 94,
                'name' => 'OSP-OCHO SUR P S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 102,
                'client_id' => 97,
                'name' => 'H20-H2OLMOS S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 103,
                'client_id' => 98,
                'name' => 'ICP-INSUMOS CORPORATIVOS PERU E.I.R.L.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 104,
                'client_id' => 99,
                'name' => 'CPI-CORPORACIÓN PESQUERA INCA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 105,
                'client_id' => 21,
                'name' => 'TRUPAL - SULLANA ',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 106,
                'client_id' => 100,
                'name' => 'MNT - MONTANA S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 107,
                'client_id' => 101,
                'name' => 'SEV - SEVIDON S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 108,
                'client_id' => 101,
                'name' => 'SON - SEVIDON S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 109,
                'client_id' => 102,
                'name' => 'ACS-AGROPECUARIA CHIMU S.R.L.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 110,
                'client_id' => 103,
                'name' => 'EPE - EL PEDREGAL S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 111,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 112,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 113,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 114,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 115,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 116,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 117,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 118,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 119,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 120,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 121,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 122,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 123,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 124,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 125,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 126,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 127,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 128,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 135,
                'client_id' => 18,
                'name' => 'ECOSAC AGRÍCOLA S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 136,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 137,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 138,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 139,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 140,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 141,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 142,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 143,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 144,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 145,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 146,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 147,
                'client_id' => 90,
                'name' => 'INDUSTRIAS TULUMAYO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 148,
                'client_id' => 99,
                'name' => 'COPEINCA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 149,
                'client_id' => 104,
                'name' => 'SCC - SAN CARLOS CONTRATISTAS GENERALES S.R.L.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 150,
                'client_id' => 105,
                'name' => 'PRA - PROCESOS AGROINDUSTRIALES S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 151,
                'client_id' => 106,
                'name' => 'UPE - UNACEM PERU S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 152,
                'client_id' => 107,
                'name' => 'CI -CALIZA CEMENTO INCA S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 153,
                'client_id' => 106,
                'name' => 'UPE - UNACEM PERU S.A.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 155,
                'client_id' => 108,
                'name' => 'DIRECCIÓN DE GESTIÓN DE RECURSOS EDUCATIVOS - DIGERE',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 156,
                'client_id' => 109,
                'name' => 'TRANSBAL EXPRESS',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 157,
                'client_id' => 110,
                'name' => 'ELECTRONORTE SA.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 158,
                'client_id' => 111,
                'name' => 'DIGERE',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 159,
                'client_id' => 112,
                'name' => 'GRP - GOBIERNO REGIONAL DE PIURA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 160,
                'client_id' => 113,
                'name' => 'EUROANDINO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 161,
                'client_id' => 114,
                'name' => 'MP',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 162,
                'client_id' => 1,
                'name' => 'CPS-CEMENTOS PACASMAYO-SELVA ',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 163,
                'client_id' => 115,
                'name' => 'ABAINCOR EIRL',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 164,
                'client_id' => 74,
                'name' => 'GCI',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 165,
                'client_id' => 116,
                'name' => 'EPM - EMPREMAR E.I.R.L.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 166,
                'client_id' => 117,
                'name' => 'PPA',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 167,
                'client_id' => 118,
                'name' => ' FLP DEL PERU S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 168,
                'client_id' => 119,
                'name' => 'WENCO',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 169,
                'client_id' => 120,
                'name' => 'FEIMI',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 170,
                'client_id' => 121,
                'name' => 'PFP',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 171,
                'client_id' => 122,
                'name' => 'OL-OLYMPIC PERU INC SUCURSAL DEL PERU',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 172,
                'client_id' => 123,
                'name' => 'TA - TAMSHI S.A.C.',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 173,
                'client_id' => 124,
                'name' => 'RA - RANSA S.A.C. ',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 174,
                'client_id' => 125,
                'name' => 'CONSORCIO AYESA- HMV',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 175,
                'client_id' => 126,
                'name' => 'SE-SEED FOOD S.A.C. ',
                'description' => null,
                'location' => null,
                'latitude' => null,
                'longitude' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];

        foreach ($data as $item) {
            SubClient::create($item);
        }
    }
}
